services:
  # Backend service
  - type: web
    name: aloha-learn-backend
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python run.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aloha-learn-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

  # Frontend service
  - type: web
    name: aloha-learn-frontend
    runtime: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: aloha-learn-db
    databaseName: aloha_learn
    user: aloha_user